{% set version = "0.0.3" %}

package:
  name: bmorph
  version: {{ version }}

source:
  url: https://github.com/UW-Hydro/bmorph/archive/refs/tags/{{ version }}.tar.gz
  sha256: c6cccfb76ecea8fbb07f2461332408532f7b417bee93b47441b7efacc598f441

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - xarray
    - pandas
    - bottleneck
    - netcdf4
    - numpy
    - scipy
    - dask
    - toolz
    - geopandas
    - seaborn
    - scikit-learn
    - tqdm
    - joblib
    - networkx
    - graphviz
    - pygraphviz
    - jupyter
    - pyproj >=3.0.0
    - mizuroute

test:
  requires:
    - python {{ python_min }}
  imports:
    - bmorph

about:
  home: https://github.com/UW-Hydro/bmorph
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'bmorph is a package for streamflow bias correction'

  description: |
      bmorph is a package for streamflow bias correction
  doc_url: http://bmorph.readthedocs.io/
  dev_url: https://github.com/UW-Hydro/bmorph

extra:
  recipe-maintainers:
    - arbennett
